#!/usr/bin/env python
"""Write the generated Reference pages of the pimm docs.

    python tools/gen_reference.py REPO_ROOT SOURCE_DIR

writes four pages under SOURCE_DIR/reference/:

* ``cli.md``: every ``pimm`` command, from its parser.
* ``recipes.md``: every config under ``configs/``, loaded with ``Config.fromfile``.
* ``api.md``: every registered component, from the registries.
* ``environment.md``: every environment variable read by ``pimm/``, ``configs/``
  and the shell scripts, found by parsing the source.

The pages are not committed. To change one, change the code it is generated from.
A file is only rewritten when its content changes, so Sphinx rebuilds stay
incremental. ``make html`` runs this before Sphinx.
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import importlib
import inspect
import io
import re
import sys
import warnings
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable

HEADER = "% Generated by docs/tools/gen_reference.py. Edit the code, not this file.\n\n"


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def cell(text: Any) -> str:
    """Make text safe for one Markdown table cell."""
    text = " ".join(str(text).split())
    return text.replace("|", "\\|") if text else "—"


def prose(text: Any) -> str:
    """Escape characters Markdown would read as HTML or emphasis, outside code spans."""
    parts = re.split(r"(`[^`]*`)", str(text or ""))
    return "".join(p if p.startswith("`") else re.sub(r"([<*])", r"\\\1", p) for p in parts)


def code(text: Any) -> str:
    text = str(text)
    fence = "``" if "`" in text else "`"
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def table(headers: list[str], rows: Iterable[list[Any]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    lines += ["| " + " | ".join(cell(value) for value in row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def summary(doc: str | None) -> str:
    """Return the first paragraph of a docstring as one line."""
    if not doc:
        return ""
    paragraph = inspect.cleandoc(doc).split("\n\n", 1)[0]
    return " ".join(paragraph.split())


def write(path: Path, text: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# Command line
# ---------------------------------------------------------------------------


class _Captured(Exception):
    def __init__(self, parser: argparse.ArgumentParser):
        self.parser = parser


def capture_parser(entry: Callable[[list[str]], Any]) -> argparse.ArgumentParser:
    """Run an argparse entry point until it parses, and return its parser."""

    def parse_args(self, *args, **kwargs):
        raise _Captured(self)

    original = argparse.ArgumentParser.parse_args
    argparse.ArgumentParser.parse_args = parse_args
    try:
        entry([])
    except _Captured as captured:
        return captured.parser
    finally:
        argparse.ArgumentParser.parse_args = original
    raise RuntimeError(f"{entry.__module__}.{entry.__name__} did not build a parser")


_DEFAULT_RE = re.compile(r"\s*\(default: (.*)\)\s*$", re.S)


def split_default(help_text: str | None) -> tuple[str, str | None]:
    """Split tyro's trailing ``(default: X)`` off a help string."""
    help_text = (help_text or "").replace("%%", "%")
    match = _DEFAULT_RE.search(help_text)
    if not match:
        return help_text.strip(), None
    return help_text[: match.start()].strip(), match.group(1)


def flag_name(action: argparse.Action) -> str:
    return " / ".join(code(option) for option in action.option_strings)


def argument_rows(parser: argparse.ArgumentParser) -> list[list[str]]:
    rows = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction, argparse._SubParsersAction)):
            continue
        if action.help == argparse.SUPPRESS:
            continue
        help_text, default = split_default(action.help)
        if action.option_strings:
            name = flag_name(action)
            if default is None and action.default not in (None, False, argparse.SUPPRESS):
                default = action.default
        else:
            name = code(action.metavar or action.dest.upper())
            if action.nargs == "?" and action.default is not None:
                default = action.default
        rows.append([name, prose(help_text), code(default) if default not in (None, "") else ""])
    return rows


def render_argparse(parser: argparse.ArgumentParser, prog: str, level: int) -> str:
    parser.prog = prog
    out = []
    description = summary(parser.description)
    if description:
        out.append(prose(description[:1].upper() + description[1:]) + "\n")
    usage = parser.format_usage().strip()
    out.append(f"```text\n{usage}\n```\n")
    rows = argument_rows(parser)
    if rows:
        out.append(table(["Argument", "Meaning", "Default"], rows))
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        helps = {choice.dest: choice.help for choice in action._choices_actions}
        for name, sub in action.choices.items():
            out.append(f"{'#' * level} `{prog} {name}`\n")
            if helps.get(name):
                sub.description = sub.description or helps[name]
            out.append(render_argparse(sub, f"{prog} {name}", level + 1))
    return "\n".join(out)


def tyro_parser(command_type: type, site: str) -> argparse.ArgumentParser:
    import tyro.extras

    from pimm.launch.config import load_config
    from pimm.launch.schema import LaunchConfig

    base = load_config(site=site, recipe=None, launch_timestamp="")
    default = command_type.from_config(LaunchConfig.from_dict(base))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        return tyro.extras.get_parser(command_type, default=default)


def tidy_metavar(metavar: str) -> str:
    """Turn tyro metavars such as ``{None}|STR`` into ``str``, ``[STR [STR ...]]`` into ``str ...``."""
    if metavar.startswith("[") and metavar.endswith("...]]"):
        return tidy_metavar(metavar[1:].split(" ", 1)[0]) + " ..."
    parts = [part for part in metavar.split("|") if part != "{None}"]
    return " | ".join(part if part.startswith("{") else part.lower() for part in parts)


def tyro_groups(parser: argparse.ArgumentParser) -> list[tuple[str, str, list[list[str]]]]:
    groups = []
    for group in parser._action_groups:
        rows = []
        for action in group._group_actions:
            if action.dest == "help" or action.help == argparse.SUPPRESS:
                continue
            help_text, default = split_default(action.help)
            metavar = tidy_metavar(action.metavar) if isinstance(action.metavar, str) else "bool"
            rows.append(
                [
                    flag_name(action),
                    code(metavar),
                    prose(help_text),
                    code(default) if default not in (None, "") else "",
                ]
            )
        if rows:
            groups.append((group.title or "", summary(group.description), rows))
    return groups


def keyword_literal(path: Path, function: str, keyword: str) -> Any:
    """Return a literal keyword argument passed inside ``function`` in ``path``."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == function:
            for call in ast.walk(node):
                if isinstance(call, ast.Call):
                    for kw in call.keywords:
                        if kw.arg == keyword:
                            return ast.literal_eval(kw.value)
    return None


def gen_cli(repo: Path) -> str:
    from pimm.cli import export, launch, main, submit, trace, watchdog
    from pimm.launch.schema import LaunchCommand, SubmitCommand

    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        main.main(["--help"])
    commands = []
    listing = buffer.getvalue().split("commands:", 1)[1]
    for line in listing.strip().splitlines():
        name, _, text = line.strip().partition(" ")
        commands.append((name, text.strip()))

    out = [HEADER, "# Command line\n"]
    out.append(
        "`pimm` is installed with the package. Run it from the checkout as `uv run pimm <command>`; "
        "every command takes `-h`.\n"
    )
    out.append(table(["Command", "Does"], [[f"[`pimm {n}`](#pimm-{n})", t] for n, t in commands]))

    sections: dict[str, str] = {}
    sections["ls"] = (
        f"{summary(main.list_configs.__doc__)} The names are paths under `configs/` without `.py`, "
        "the form `--train.config` takes.\n\n```text\nusage: pimm ls [DIRECTORY ...]\n```\n"
    )

    launch_parser = tyro_parser(LaunchCommand, site="local")
    text = [summary(launch.__doc__) + "\n"]
    text.append(
        "```text\nusage: pimm launch [FLAGS] [-- KEY=VALUE ...]\n```\n\n"
        "Flags set the launch config; `KEY=VALUE` tokens after a bare `--` override the experiment "
        "config (see [Configs and overrides](../training/configs.md)). Defaults below come from "
        "`launch/defaults.yaml` and the `local` site profile; `--site` and `--recipe` load others.\n"
    )
    for title, description, rows in tyro_groups(launch_parser):
        heading = "General" if title == "options" else f"`--{title.removesuffix(' options')}.*`"
        text.append(f"### {heading}\n")
        if description:
            text.append(description + "\n")
        text.append(table(["Flag", "Type", "Meaning", "Default"], rows))
    sections["launch"] = "\n".join(text)

    launch_flags = {a.dest for a in launch_parser._actions}
    submit_parser = tyro_parser(SubmitCommand, site="local")
    extra = [a for a in submit_parser._actions if a.dest not in launch_flags]
    default_site = keyword_literal(Path(submit.__file__), "parse_command", "default_site")
    text = [summary(submit.__doc__) + "\n"]
    text.append(
        "```text\nusage: pimm submit [FLAGS] [-- KEY=VALUE ...]\n```\n\n"
        "`pimm submit` takes every [`pimm launch`](#pimm-launch) flag"
        + (f", with `--site` defaulting to `{default_site}`" if default_site else "")
        + ", plus:\n"
    )
    rows = []
    for action in extra:
        help_text, default = split_default(action.help)
        rows.append([flag_name(action), prose(help_text), code(default) if default else ""])
    text.append(table(["Flag", "Meaning", "Default"], rows))
    sections["submit"] = "\n".join(text)

    for name, module in (("watchdog", watchdog), ("trace", trace), ("export", export)):
        entry = getattr(module, "parse_args", None) or module.main
        parser = capture_parser(entry)
        parser.description = parser.description or module.__doc__
        sections[name] = render_argparse(parser, f"pimm {name}", level=3)

    for name, _ in commands:
        out.append(f"## `pimm {name}`\n")
        if name not in sections:
            raise RuntimeError(f"no reference section for `pimm {name}`")
        out.append(sections.get(name, "") or "")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Recipe catalog
# ---------------------------------------------------------------------------


def _type(value: Any) -> str | None:
    return value.get("type") if isinstance(value, dict) else None


def gen_recipes(repo: Path) -> tuple[str, list[str]]:
    from pimm.utils.config import Config

    configs = repo / "configs"
    groups: dict[str, list[list[str]]] = defaultdict(list)
    failures: list[tuple[str, str]] = []
    for path in sorted(configs.rglob("*.py")):
        rel = path.relative_to(configs)
        if any(part.startswith("_") for part in rel.parts):
            continue
        name = rel.with_suffix("").as_posix()
        about = summary(ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))))
        try:
            cfg = Config.fromfile(str(path))
        except Exception as error:  # report, keep going
            failures.append((name, f"{type(error).__name__}: {error}".replace(str(repo) + "/", "")))
            continue
        model = cfg.get("model", {})
        backbone = model.get("backbone") if isinstance(model, dict) else None
        model_text = " · ".join(code(t) for t in (_type(model), _type(backbone)) if t)
        data = cfg.get("data", {})
        train = data.get("train", {}) if isinstance(data, dict) else {}
        data_text = code(_type(train)) if _type(train) else ""
        if isinstance(train, dict) and train.get("revision"):
            data_text += f" {train['revision']}"
        weight = cfg.get("weight")
        groups[rel.parent.as_posix()].append(
            [
                code(name),
                prose(about),
                model_text,
                data_text,
                code(weight) if weight else "",
                cfg.get("epoch", ""),
                cfg.get("batch_size", ""),
            ]
        )

    count = sum(len(rows) for rows in groups.values())
    out = [HEADER, "# Recipe catalog\n"]
    out.append(
        f"pimm ships {count} recipes. A recipe is a config under `configs/`; pass its name to "
        "`--train.config`. `uv run pimm ls` prints the same names. Batch size counts events per "
        "step across all GPUs. A blank warm start means the recipe starts from random weights "
        "unless you pass `--train.weight`.\n"
    )
    for group in sorted(groups):
        out.append(f"## {group}\n")
        out.append(
            table(
                ["Recipe", "About", "Model", "Data", "Warm start", "Epochs", "Batch size"],
                groups[group],
            )
        )
    if failures:
        out.append("## Recipes that don't load\n")
        out.append(
            "These configs fail in `Config.fromfile`, so neither the catalog nor the launcher can use them.\n"
        )
        out.append(table(["Recipe", "Error"], [[code(n), e] for n, e in failures]))
    return "\n".join(out), [f"{n}: {e}" for n, e in failures]


# ---------------------------------------------------------------------------
# Python API
# ---------------------------------------------------------------------------

REGISTRIES = [
    # (heading, module, attribute, what a config uses it for)
    ("Models", "pimm.models.builder", "MODELS", "`model.type` and nested `backbone.type`"),
    ("Datasets", "pimm.datasets.builder", "DATASETS", "`data.<split>.type`"),
    ("Transforms", "pimm.datasets.transform.common", "TRANSFORMS", "entries of `transform` lists"),
    ("Losses", "pimm.models.losses.builder", "LOSSES", "entries of `criteria` lists"),
    ("Hooks", "pimm.engines.hooks.builder", "HOOKS", "entries of `hooks`"),
    ("Trainers", "pimm.engines.train", "TRAINERS", "`train.type`"),
    ("Testers", "pimm.engines.test", "TESTERS", "`test.type`"),
    ("Optimizers", "pimm.utils.optimizer", "OPTIMIZERS", "`optimizer.type`"),
    ("Schedulers", "pimm.utils.scheduler", "SCHEDULERS", "`scheduler.type`"),
]


def gen_api(repo: Path) -> str:
    for package in ("pimm.models", "pimm.datasets", "pimm.engines.hooks"):
        importlib.import_module(package)

    out = [HEADER, "# Python API\n"]
    out.append(
        "Each component in a config is a dict whose `type` is a name registered here; pimm builds "
        "the class with the dict's other keys. Summaries are the first paragraph of each class's "
        "docstring. To add a name, see [Add a component](../develop/add-component.md).\n"
    )
    sections = []
    for heading, module_name, attribute, used in REGISTRIES:
        registry = getattr(importlib.import_module(module_name), attribute)
        items = registry.module_dict
        if not items:
            continue
        rows = []
        for name in sorted(items, key=str.lower):
            cls = items[name]
            rows.append(
                [
                    code(name),
                    code(f"{cls.__module__}.{cls.__qualname__}"),
                    prose(summary(cls.__dict__.get("__doc__"))),
                ]
            )
        sections.append((heading, len(items), used, rows))

    out.append(
        table(
            ["Registry", "Names", "Used for"],
            [[f"[{h}](#{h.lower()})", n, u] for h, n, u, _ in sections],
        )
    )
    for heading, _, _, rows in sections:
        out.append(f"## {heading}\n")
        out.append(table(["Name", "Class", "Summary"], rows))
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Environment variables
# ---------------------------------------------------------------------------

AREAS = [
    # (heading, path prefixes), first match wins
    ("Data", ("pimm/datasets/", "configs/")),
    (
        "Checkpoints and downloads",
        ("pimm/utils/checkpoints.py", "pimm/utils/path.py", "pimm/export"),
    ),
    ("Distributed runs and Slurm", ("pimm/utils/comm.py",)),
    ("Launcher and job scripts", ("pimm/launch/", "pimm/cli/", "scripts/")),
    ("Training", ("pimm/engines/", "pimm/models/", "pimm/train.py")),
    ("Logging and traces", ("pimm/observability/",)),
]
SHELL_IGNORE = {"OPTARG", "OPTIND", "IFS", "PWD", "HOME", "PATH"}


@dataclass
class EnvRead:
    path: str
    line: int
    where: str
    note: str
    default: str | None


@dataclass
class EnvVar:
    name: str
    reads: list[EnvRead] = field(default_factory=list)


def _first_sentence(text: str) -> str:
    match = re.match(r"(.+?[.!?])(\s|$)", text)
    return match.group(1) if match else text


def _comment(lines: list[str], lineno: int, name: str) -> str:
    """Return the comment that describes a read, or "".

    That is the comment on the same line, or the comment block right above it when
    the block is at most two lines or names the variable. Only its first sentence
    is kept.
    """
    line = lines[lineno - 1]
    if "#" in line and not line.lstrip().startswith("#"):
        trailing = line.split("#", 1)[1].strip()
        if trailing and not trailing.startswith(("noqa", "type:", "pragma")):
            return _first_sentence(trailing)
    block = []
    index = lineno - 2
    while index >= 0 and lines[index].lstrip().startswith("#"):
        block.insert(0, lines[index].strip().lstrip("#").strip())
        index -= 1
    block = [part for part in block if part and not set(part) <= set("─-=#")]
    stem = name.split("<", 1)[0]
    if not block or (len(block) > 2 and stem not in " ".join(block)):
        return ""
    return _first_sentence(" ".join(block))


class _EnvVisitor(ast.NodeVisitor):
    def __init__(self, constants: dict[str, str]):
        self.constants = constants
        self.scopes: list[ast.AST] = []
        self.loops: dict[str, list[str]] = {}
        self.found: list[tuple[str, int, str, str | None]] = []

    @staticmethod
    def _is_environ(node: ast.AST) -> bool:
        return (
            isinstance(node, ast.Attribute)
            and node.attr == "environ"
            and isinstance(node.value, ast.Name)
            and node.value.id == "os"
        )

    def _where(self) -> str:
        names = [
            s.name
            for s in self.scopes
            if isinstance(s, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
        ]
        return ".".join(names) or "module"

    def _local_value(self, name: str) -> ast.AST | None:
        for scope in reversed(self.scopes):
            for node in ast.walk(scope):
                if isinstance(node, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == name for t in node.targets
                ):
                    return node.value
        return None

    def _names(self, node: ast.AST) -> list[str]:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return [node.value]
        if isinstance(node, ast.Name):
            value = self._local_value(node.id)
            if value is not None:
                return self._names(value)
            if node.id in self.constants:
                return [self.constants[node.id]]
            return []
        if isinstance(node, ast.JoinedStr):
            variants = [""]
            for part in node.values:
                if isinstance(part, ast.Constant):
                    variants = [v + str(part.value) for v in variants]
                    continue
                expr = part.value
                base = (
                    expr.func.value
                    if (
                        isinstance(expr, ast.Call)
                        and isinstance(expr.func, ast.Attribute)
                        and expr.func.attr == "upper"
                    )
                    else expr
                )
                choices = self.loops.get(base.id) if isinstance(base, ast.Name) else None
                if choices:
                    variants = [v + c.upper() for v in variants for c in choices]
                else:
                    label = base.id if isinstance(base, ast.Name) else ast.unparse(base)
                    variants = [v + f"<{label.upper()}>" for v in variants]
            return variants
        return []

    def _record(self, node: ast.AST, key: ast.AST, default: ast.AST | None = None) -> None:
        text = None
        if default is not None:
            try:
                value = ast.literal_eval(default)
                text = None if value is None else (value if isinstance(value, str) else repr(value))
            except ValueError:
                text = None
        for name in self._names(key):
            self.found.append((name, node.lineno, self._where(), text))

    def visit_FunctionDef(self, node):
        self.scopes.append(node)
        self.generic_visit(node)
        self.scopes.pop()

    visit_AsyncFunctionDef = visit_FunctionDef
    visit_ClassDef = visit_FunctionDef

    def visit_For(self, node):
        if isinstance(node.target, ast.Name) and isinstance(node.iter, (ast.Tuple, ast.List)):
            values = [
                e.value
                for e in node.iter.elts
                if isinstance(e, ast.Constant) and isinstance(e.value, str)
            ]
            if len(values) == len(node.iter.elts):
                self.loops[node.target.id] = values
        self.generic_visit(node)
        if isinstance(node.target, ast.Name):
            self.loops.pop(node.target.id, None)

    def visit_Call(self, node):
        func = node.func
        if node.args and isinstance(func, ast.Attribute):
            default = node.args[1] if len(node.args) > 1 else None
            if func.attr in ("get", "setdefault", "pop") and self._is_environ(func.value):
                self._record(node, node.args[0], default)
            elif (
                func.attr == "getenv" and isinstance(func.value, ast.Name) and func.value.id == "os"
            ):
                self._record(node, node.args[0], default)
        self.generic_visit(node)

    def visit_Subscript(self, node):
        if self._is_environ(node.value) and isinstance(node.ctx, ast.Load):
            self._record(node, node.slice)
        self.generic_visit(node)

    def visit_Compare(self, node):
        if (
            len(node.ops) == 1
            and isinstance(node.ops[0], (ast.In, ast.NotIn))
            and self._is_environ(node.comparators[0])
        ):
            self._record(node, node.left)
        self.generic_visit(node)


def _module_constants(files: list[Path]) -> dict[str, str]:
    """Module-level ``NAME = "string"`` assignments; names bound twice are dropped."""
    seen: dict[str, set[str]] = defaultdict(set)
    for path in files:
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        for node in tree.body:
            if (
                isinstance(node, ast.Assign)
                and isinstance(node.value, ast.Constant)
                and isinstance(node.value.value, str)
            ):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        seen[target.id].add(node.value.value)
    return {name: values.pop() for name, values in seen.items() if len(values) == 1}


_SH_DEFAULTED = re.compile(r"\$\{([A-Z][A-Z0-9_]*):?[-=]([^}$]*)\}")
_SH_READ = re.compile(r"\$\{?([A-Z][A-Z0-9_]*)")
_SH_ASSIGN = re.compile(r"(?:^|[\s;&|(])(?:export\s+|local\s+|readonly\s+)?([A-Z][A-Z0-9_]*)=")
_SH_BIND = re.compile(r"\b(?:read(?:\s+-\w+)*|for|getopts\s+\S+)\s+([A-Z][A-Z0-9_]*)")


def _shell_reads(path: Path) -> list[tuple[str, int, str | None]]:
    """Variables a script reads from its environment.

    A variable counts when it is expanded with a default (``${X:-...}``), or when it
    is expanded but never assigned in the script.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    assigned: set[str] = set()
    for line in lines:
        if line.lstrip().startswith("#"):
            continue
        assigned.update(_SH_ASSIGN.findall(line))
        assigned.update(_SH_BIND.findall(line))
    found: dict[str, int] = {}
    defaults: dict[str, str] = {}
    in_heredoc = None
    for lineno, line in enumerate(lines, 1):
        if in_heredoc:
            if line.strip() == in_heredoc:
                in_heredoc = None
            continue
        heredoc = re.search(r"<<-?\s*'([A-Z]+)'", line)
        if heredoc:
            in_heredoc = heredoc.group(1)
        if line.lstrip().startswith("#"):
            continue
        for name, default in _SH_DEFAULTED.findall(line):
            found.setdefault(name, lineno)
            if default:
                defaults.setdefault(name, default)
        for name in _SH_READ.findall(line):
            if name not in assigned:
                found.setdefault(name, lineno)
    return [(n, l, defaults.get(n)) for n, l in found.items() if n not in SHELL_IGNORE]


def collect_env(repo: Path) -> dict[str, EnvVar]:
    py_files = sorted(
        p
        for root in ("pimm", "configs")
        for p in (repo / root).rglob("*.py")
        if "__pycache__" not in p.parts
    )
    constants = _module_constants([p for p in py_files if p.is_relative_to(repo / "pimm")])
    found: dict[str, EnvVar] = {}

    def add(
        name: str, rel: str, lineno: int, where: str, default: str | None, lines: list[str]
    ) -> None:
        var = found.setdefault(name, EnvVar(name))
        var.reads.append(EnvRead(rel, lineno, where, _comment(lines, lineno, name), default))

    for path in py_files:
        text = path.read_text(encoding="utf-8")
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        visitor = _EnvVisitor(constants)
        visitor.visit(tree)
        lines = text.splitlines()
        rel = path.relative_to(repo).as_posix()
        for name, lineno, where, default in visitor.found:
            add(name, rel, lineno, where, default, lines)

    shell_files = sorted((repo / "scripts").rglob("*.sh")) + sorted((repo / "pimm").rglob("*.sh"))
    for path in shell_files:
        lines = path.read_text(encoding="utf-8").splitlines()
        rel = path.relative_to(repo).as_posix()
        for name, lineno, default in _shell_reads(path):
            add(name, rel, lineno, "script", default, lines)
    return found


def _area(path: str) -> int:
    for index, (_, prefixes) in enumerate(AREAS):
        if path.startswith(prefixes):
            return index
    return len(AREAS)


def gen_environment(repo: Path) -> str:
    variables = collect_env(repo)
    by_area: dict[int, list[EnvVar]] = defaultdict(list)
    for var in variables.values():
        by_area[min(_area(r.path) for r in var.reads)].append(var)

    out = [HEADER, "# Environment variables\n"]
    out.append(
        f"pimm reads these {len(variables)} variables. `scripts/train.sh` first sources a `.env` "
        "file at the repository root, so assignments there reach every training process. "
        "`<NAME>` stands for part of a variable name filled in at run time, such as a dataset "
        "revision. A default is the value the code falls back to when the variable is unset. "
        "Libraries pimm uses, such as PyTorch, W&B and the Hugging Face Hub, read their "
        "own variables, which aren't listed.\n"
    )
    headings = [h for h, _ in AREAS] + ["Other"]
    for index in sorted(by_area):
        out.append(f"## {headings[index]}\n")
        rows = []
        for var in sorted(by_area[index], key=lambda v: v.name):
            places = []
            for read in var.reads:
                place = (
                    read.path
                    if read.where in ("module", "script")
                    else f"{read.path} ({read.where})"
                )
                if place not in places:
                    places.append(place)
            notes = list(dict.fromkeys(read.note for read in var.reads if read.note))[:2]
            defaults = list(dict.fromkeys(read.default for read in var.reads if read.default))
            rows.append(
                [
                    code(var.name),
                    ", ".join(code(d) for d in defaults),
                    ", ".join(code(p) for p in places),
                    prose(" ".join(notes)),
                ]
            )
        out.append(table(["Variable", "Default", "Read in", "Note in the code"], rows))
    return "\n".join(out)


# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("repo_root", type=Path)
    parser.add_argument("source_dir", type=Path)
    args = parser.parse_args(argv)
    repo = args.repo_root.resolve()
    reference = args.source_dir.resolve() / "reference"
    sys.path.insert(0, str(repo))

    recipes, failures = gen_recipes(repo)
    pages = {
        "cli.md": gen_cli(repo),
        "recipes.md": recipes,
        "api.md": gen_api(repo),
        "environment.md": gen_environment(repo),
    }
    for name, text in pages.items():
        changed = write(reference / name, text.rstrip() + "\n")
        print(f"gen_reference: {'wrote' if changed else 'unchanged'} reference/{name}")
    for failure in failures:
        print(f"gen_reference: warning: recipe doesn't load: {failure}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
